export {getSections} from './sections-api'
export {getFilms} from './films-api'
export {getPeople} from './people-api'
export {getPlanets} from './planets-api'
export {getSpecies} from './species-api'
export {getStarships} from './starships-api'
export {getVehicles} from './vehicles-api'